"""Add is_seed_data flag to stadiums, boxes, users

Revision ID: 33e76c98013c
Revises: e85c0df0303b
Create Date: 2026-08-23 17:27:13.560055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e76c98013c'
down_revision: Union[str, Sequence[str], None] = 'e85c0df0303b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seed_data', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('stadiums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seed_data', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seed_data', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_seed_data')

    with op.batch_alter_table('stadiums', schema=None) as batch_op:
        batch_op.drop_column('is_seed_data')

    with op.batch_alter_table('boxes', schema=None) as batch_op:
        batch_op.drop_column('is_seed_data')

    # ### end Alembic commands ###
