"""Add response deadline tracking to rent_requests

Revision ID: 36375a10f755
Revises: 33e76c98013c
Create Date: 2026-08-23 18:15:25.180544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36375a10f755'
down_revision: Union[str, Sequence[str], None] = '33e76c98013c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respond_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('owner_notified_at', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_at', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent_requests', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent_at')
        batch_op.drop_column('owner_notified_at')
        batch_op.drop_column('respond_by')

    # ### end Alembic commands ###
