"""Add event details to rent_requests and box_requests

Revision ID: c241d612a770
Revises: 36375a10f755
Create Date: 2026-08-26 11:50:17.555228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c241d612a770'
down_revision: Union[str, Sequence[str], None] = '36375a10f755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expected_guests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_guests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('needs_catering', sa.Boolean(), nullable=True))

    with op.batch_alter_table('rent_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expected_guests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_guests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('needs_catering', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent_requests', schema=None) as batch_op:
        batch_op.drop_column('needs_catering')
        batch_op.drop_column('max_guests')
        batch_op.drop_column('expected_guests')
        batch_op.drop_column('company')
        batch_op.drop_column('event_type')

    with op.batch_alter_table('box_requests', schema=None) as batch_op:
        batch_op.drop_column('needs_catering')
        batch_op.drop_column('max_guests')
        batch_op.drop_column('expected_guests')
        batch_op.drop_column('company')
        batch_op.drop_column('event_type')

    # ### end Alembic commands ###
