"""initial schema

Revision ID: e85c0df0303b
Revises: 
Create Date: 2026-07-12 09:05:46.383837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85c0df0303b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadiums',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('social_media', sa.JSON(), nullable=False),
    sa.Column('payment_method', sa.JSON(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_code', sa.String(length=6), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('boxes',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.String(length=12), nullable=False),
    sa.Column('stadium_id', sa.String(length=12), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location_in_stadium', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('box_id', sa.String(length=12), nullable=False),
    sa.Column('stadium_id', sa.String(length=12), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('price_rented', sa.Float(), nullable=False),
    sa.Column('price_owner_received', sa.Float(), nullable=False),
    sa.Column('renter_name', sa.String(), nullable=False),
    sa.Column('location_in_stadium', sa.String(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('box_requests',
    sa.Column('request_id', sa.String(length=12), nullable=False),
    sa.Column('box_id', sa.String(length=12), nullable=False),
    sa.Column('renter_id', sa.String(length=12), nullable=False),
    sa.Column('renter_name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('renter_history', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('requested_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('listings',
    sa.Column('listing_id', sa.String(length=12), nullable=False),
    sa.Column('box_id', sa.String(length=12), nullable=False),
    sa.Column('stadium_id', sa.String(length=12), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location_in_stadium', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('rent_requests',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('box_id', sa.String(length=12), nullable=False),
    sa.Column('listing_id', sa.String(length=12), nullable=False),
    sa.Column('renter_id', sa.String(length=12), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('renter_snapshot', sa.JSON(), nullable=False),
    sa.Column('payment', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('survey', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent_requests')
    op.drop_table('listings')
    op.drop_table('box_requests')
    op.drop_table('booking_records')
    op.drop_table('boxes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('stadiums')
    # ### end Alembic commands ###
